### ISSUE TITLE
[DOCS] Criar um README.md contendo informações essenciais sobre o projeto

### ISSUE THREAD

**Issue by ewerton-silva00** [onobrerodrigo/Proxmox-VMManager#1]
Recomendo criar um README.md contendo informações essenciais sobre o projeto, como: objetivos, pré-requisitos para executar o script (caso precise).

Se possível, fornecer um arquivo .vmlist devidamente populado para testes locais.

**Comment by onobrerodrigo** [comment]
Solved issue.

Add a README.md and a vm files in project.
